spring:
  datasource:
    name: test
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/huan
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 80
  session:
    timeout: 1800
    
    